"""Initial

Revision ID: 5c1164b3db97
Revises: 647acd9ff244
Create Date: 2025-12-18 04:48:52.337402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c1164b3db97'
down_revision = '647acd9ff244'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###